---
title: "Codebuch NDS"
author: "K, A, I, Da, De"
date: "2024-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Codebuch NDS

***Edge-Attribute*** 

**id:** codiert mit Kürzel; jede ID entspricht einem Solokünstler, einer Veranstaltung oder einem Label

**from,to:** 
Solokünstler...zu anderem Solokünstler/zu einer Veranstaltung/zu einem Label;
Veranstalter zu Solokünstler;
Label zu Solokünstler

**weight:** Art der Beziehung zwischen den einzelnen Knoten;
1 = schwache Beziehung (kennen sich),
2 = (arbeiten zusammen, häufige Treffen)

**relation:**
1 = familiar (Interaktion Social Media - folgen sich, kommentieren...),
2 = cooperation (Zusammenarbeit mit Label, Veranstalter oder gemeinsame Features),
3 = close relationship (Bandmitglied, sympathisieren)
4 = Geschäftsführer*in
5 = Mitglied

***Node-Attribute***

**id:** identische ID wie aus der edgelist zur Identifikation der Knoten (als Kürzel)

**name:** character ID

**name_real:** Vor- und Zuname

**type:** 1 = Solokünstler, 2 = Band/Zusammenschluss, 3 = Veranstaltung, 4 = Label, 5 = Unternehmen, 6 = Aktivist, 7 = Organisation 

**sex:** Geschlecht bei Solokünstlern:
1 = männlich, 2 = weiblich, 3 = divers

**age_real:** Alter in natürlichen Zahlen

**politics:** Parteimitgliedschaft/Mitglied einer politischen Organisation; werden als string/characters codiert

**spotify-listener:** monatliche Hörer; als natürliche Zahl codiert

**county:** Wohnort (Bundesland); als string/characters codiert

**exit:** ja/nein

