---
title: "Codebuch NS-Rap"
author: "k135, ag194, iv011, dr093, db149"
date: "2024-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Codebuch NS-Rap

***Edge-Attribute*** 

**id:** codiert mit Kürzel; jede ID entspricht einem Solokünstler, einer Veranstaltung oder einem Label

**from,to:** 
Solokünstler...zu anderem Solokünstler/zu einer Veranstaltung/zu einem Label;
Veranstalter zu Solokünstler;
Label zu Solokünstler

**weight:** Art der Beziehung zwischen den einzelnen Knoten;
1 = schwache Beziehung (kennen sich),
2 = (arbeiten zusammen, häufige Treffen)

**relation:**
1 = familiar (Interaktion Social Media - folgen sich, kommentieren...),
2 = cooperation (Zusammenarbeit mit Label, Veranstalter oder gemeinsame Features),
3 = close relationship (Bandmitglied, sympathisieren)


***Node-Attribute***

**id:** identische ID wie aus der edgelist zur Identifikation der Knoten (als Kürzel)

**name:** Klarname des Künstlers oder des Labels; character ID

**type:** 1 = Solokünstler, 2 = Band/Zusammenschluss, 3 = Veranstaltung, 4 = Label

**sex:** Geschlecht bei Solokünstlern:
1 = männlich, 2 = weiblich, 3 = divers

**age_real:** Alter in natürlichen Zahlen

**politics:** Parteimitgliedschaft/Mitglied einer politischen Organisation; werden als string/characters codiert

**spotify-listener:** monatliche Hörer; als natürliche Zahl codiert

**criminal:** eingetragene oder fallengelassene Straftaten; als characters codiert: ja/nein

**religion:** Glaubensrichtung (christlich, bhuddistisch, islamisch)

**county:** Wohnort des Solokünstlers oder Sitz des Labels/Veranstaltung (Bundesland); als string/characters codiert

**born in:** Geburtsort (Bundesland); als string/characters codiert

**start:** Beginn der Karriere des Solokünstlers/Gründungsjahr der Band; z.B. 2003

**exit:** Ausstiegsjahr des Solokünstlers/Band; z.B. 2019


