---
title: "NDS Rap pretest"
author: "Isabelle Vees"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# l채dt die Programmbibliotheken
library(tidyverse)
library(igraph)
install.packages("visNetwork")
```

```{r}
# Einlesen der Edge- und Nodelist
edges <- read.csv("https://raw.githubusercontent.com/IsabelleVees/SNA-NDS/main/nds_edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/IsabelleVees/SNA-NDS/main/nds_nodes.csv", header=T, as.is=T, sep = ",")

# Matrix erstellen
edgematrix <-as.matrix(edges)


# Zusammenf체hren von Edge- und Nodelist als igraph-Objekt rb
nsr <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=F)

# Aufrufen der Netzwerks
nsr

# Namen als ids festlegen

V(nsr)$label <- nodes$id

# Netzwerk anzeigen


# der folgende Plot ist um einige weitere Visualisierungsparameter erg채nzt
plot(nsr,)

plot(nsr, 
     layout = layout_with_fr(nsr),  
     vertex.size = 15,               
     vertex.color = "lightblue",    
     vertex.label.cex = 0.35,         
     vertex.label.color = "black",
     vertex.label.font = 2, # 2 steht f체r fett
     edge.width = 1.5,                 
     edge.color = "gray",            
     main = "Pretest NDS"  
)
```



